import Head from "next/head";

import { useAuth } from "@/lib/firebase/auth";

export default function Home() {
  const auth = useAuth();

  return (
    <>
      <Head>
        <title>Get Feedback App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => auth.signinWithGithub()}>Sign In</button>
        <div>
          {auth?.user?.name} <span>{auth?.user?.email}</span>
        </div>
        {auth?.user && <button onClick={() => auth.signout()}>Sign Out</button>}
      </main>
    </>
  );
}
